### ISSUE TITLE
tac-0.3.10.5 / 0.3.11.2 crash on 1.16.5

### ISSUE THREAD

**Issue by gade260** [ClumsyAlien/TimelessandClassics_Reforged#176]
经测试，tac-0.3.10.5 / 0.3.11.2 在1.16.5（client）会崩溃，但是在forge-server不会崩溃
launcher: HMCL
return: crush
账户：离线（非正版）
Crash Report UUID: b1057dcd-99bb-4cf7-964c-2b3698ff81c4

crash-log:
Time: 2024/1/28 下午6:40
Description: Unexpected error

java.lang.NegativeArraySizeException: -1
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.41.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Alibaba
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Alibaba
	Memory: 1275881104 bytes (1216 MB) / 2181038080 bytes (2080 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 12 total; -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.41.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.41.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.41
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.41-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.41-universal.jar                |Forge                         |forge                         |36.2.41             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tac-release-0.3.10.5-1.16.5.jar                   |Timeless and Classics Guns    |tac                           |0.3.10.5            |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: b1057dcd-99bb-4cf7-964c-2b3698ff81c4
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.5161, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz

**Comment by manilovethis** [comment]
TAC fucks with the game renderer, SOMEHOW, so you probably may need to allocate atleast 4 gigs of memory. or i suggest you stick with 3.9 or something, since the newer versions arent all that stable.
