### ISSUE TITLE
An error occurred when using mod on the server

### ISSUE THREAD

**Issue by Fish-MilkShake** [ClumsyAlien/TimelessandClassics_Reforged#33]
Fragment log：
[00:09:35] [Server thread/WARN]: Fish_UY(59f2125c-d9d5-3224-a6e2-03faf179807c) tried to fire before cooldown finished or server is lagging? Remaining milliseconds: 84
[00:09:35] [Server thread/FATAL]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[00:09:35] [Server thread/FATAL]: Error executing task on Server
 java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:73) ~[CatServer-1.16.5-76952803-server.jar:36.2]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.tac.guns.common.network.ServerPlayHandler.handleShoot(ServerPlayHandler.java:114) ~[tac:0.2.1.1-1.16.5]
        at com.tac.guns.network.message.MessageShoot.lambda$handle$0(MessageShoot.java:49) ~[tac:0.2.1.1-1.16.5]
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
        at com.tac.guns.network.message.MessageShoot.handle(MessageShoot.java:44) ~[tac:0.2.1.1-1.16.5]
        at com.tac.guns.network.PacketHandler.lambda$registerPlayMessage$7(PacketHandler.java:92) ~[tac:0.2.1.1-1.16.5]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2571) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:50) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:13) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:884) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:867) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:861) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:847) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:779) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
The second：
[00:00:53] [Server thread/FATAL]: Error executing task on Server
 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at com.tac.guns.common.network.ServerPlayHandler.handleFireMode(ServerPlayHandler.java:418) ~[tac:0.2.1.1-1.16.5]
        at com.tac.guns.network.message.MessageFireMode.lambda$handle$0(MessageFireMode.java:34) ~[tac:0.2.1.1-1.16.5]
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
        at com.tac.guns.network.message.MessageFireMode.handle(MessageFireMode.java:29) ~[tac:0.2.1.1-1.16.5]
        at com.tac.guns.network.PacketHandler.lambda$registerPlayMessage$7(PacketHandler.java:92) ~[tac:0.2.1.1-1.16.5]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[CatServer-1.16.5-76952803-server.jar:?]
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2571) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:50) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:13) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:884) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:867) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:861) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:847) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:779) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Complete server logs：

[debug.log](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/9200918/debug.log)
[latest.log](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/9200921/latest.log)

**Comment by ClumsyAlien** [comment]
This post is missing Critical information.

What mods and versions are running, along with what action was being taken before this error occurred.

And is this error a crash level error or just logs.

**Comment by Fish-MilkShake** [comment]
Supplement:

Server: catserver-1.16.5-76952803-server

Game Version: 1.16.5

This error is a frequent log

The error occurred because of the frequent firing

**Comment by ClumsyAlien** [comment]
Does this error crash your game/server or just a log? So far I only am seeing more informative logs, once that actually mean mod function is working as expected, also what mod versions do you have, I do understand your on Minecraft 1.16.5.

**Comment by Fish-MilkShake** [comment]
This error is a logging error
This is the list of module
![list](https://user-images.githubusercontent.com/108009245/181302899-d65e3b5a-dd90-44ac-90fe-e17cec366af3.png)
I wonder if there is any problem with such a mistake
If not, then sorry to bother you

**Comment by ClumsyAlien** [comment]
Everything looks correct, no need for sorries, if the server runs without major issue or crashes then it means these errors are handled, working properly in my eyes for now.

**Comment by Fish-MilkShake** [comment]
Thanks to answer

**Comment by ClumsyAlien** [comment]
Your welcome
