### ISSUE TITLE
ServerCrash java.lang.StackOverflowError: Exception in server tick loop 🐛 ❓ 

### ISSUE THREAD

**Issue by coperkk** [ClumsyAlien/TimelessandClassics_Reforged#38]
[file](https://drive.google.com/file/d/1Wa_QGnGnaU9B8bcbVpYwsgB6EBxivo1B/view?usp=sharing)

I am in the Ocean shoot the Guardian,After Server Crash

I think Main problem  is 
	at com.tac.guns.entity.ProjectileEntity.func_70071_h_(ProjectileEntity.java:219) ~[tac:0.2.1.1-1.16.5] {re:classloading}
	at com.tac.guns.entity.ProjectileEntity.onHitBlock(ProjectileEntity.java:556) ~[tac:0.2.1.1-1.16.5] {re:classloading}
	at com.tac.guns.entity.ProjectileEntity.onHit(ProjectileEntity.java:456) ~[tac:0.2.1.1-1.16.5] {re:classloading}

But I am not sure is true I don,t understand what happen on the server

**Comment by ClumsyAlien** [comment]
Update to the latest public version of TaC on Curseforge.
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
