### ISSUE TITLE
ava.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2

### ISSUE THREAD

**Issue by TheHecateII** [ClumsyAlien/TimelessandClassics_Reforged#70]
**This error appears when you change the firing selector and put it back on "safety".**

`[22:56:38 FATAL]: Error executing task on Server
[22:56:38 WARN]: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2
[22:56:38 WARN]:        at com.tac.guns.common.network.ServerPlayHandler.handleFireMode(ServerPlayHandler.java:455)
[22:56:38 WARN]:        at com.tac.guns.network.message.MessageFireMode.lambda$handle$0(MessageFireMode.java:34)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:203)
[22:56:38 WARN]:        at com.tac.guns.network.message.MessageFireMode.handle(MessageFireMode.java:29)
[22:56:38 WARN]:        at com.tac.guns.network.PacketHandler.lambda$registerPlayMessage$8(PacketHandler.java:113)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114)
[22:56:38 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66)
[22:56:38 WARN]:        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:248)
[22:56:38 WARN]:        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:240)
[22:56:38 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
[22:56:38 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80)
[22:56:38 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[22:56:38 WARN]:        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80)
[22:56:38 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2617)
[22:56:38 WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42)
[22:56:38 WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12)
[22:56:38 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[22:56:38 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[22:56:38 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[22:56:38 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:939)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
[22:56:38 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:922)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916)
[22:56:38 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:902)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:822)
[22:56:38 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[22:56:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:857)`

**Comment by ClumsyAlien** [comment]
Does this cause any crashing within client or server? Or is this just a log.

**Comment by TheHecateII** [comment]
This is only a console error. Nevertheless it makes reading the server side logs more or less complicated

**Comment by ClumsyAlien** [comment]
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac/files/4398660
