### ISSUE TITLE
This error appears when changing the weapon's fire mode. Server: Mohist/Magma 1.16.5

### ISSUE THREAD

**Issue by Gabirubs** [ClumsyAlien/TimelessandClassics_Reforged#71]
[00:04:31 FATAL]: Error executing task on Server
[00:04:31 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[00:04:31 WARN]:        at com.tac.guns.common.network.ServerPlayHandler.handleFireMode(ServerPlayHandler.java:455)
[00:04:31 WARN]:        at com.tac.guns.network.message.MessageFireMode.lambda$handle$0(MessageFireMode.java:34)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:203)
[00:04:31 WARN]:        at com.tac.guns.network.message.MessageFireMode.handle(MessageFireMode.java:29)
[00:04:31 WARN]:        at com.tac.guns.network.PacketHandler.lambda$registerPlayMessage$8(PacketHandler.java:113)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114)
[00:04:31 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:183)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66)
[00:04:31 WARN]:        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:248)
[00:04:31 WARN]:        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:240)
[00:04:31 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
[00:04:31 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80)
[00:04:31 WARN]:        at java.base/java.util.Optional.map(Optional.java:265)
[00:04:31 WARN]:        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80)
[00:04:31 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2613)
[00:04:31 WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42)
[00:04:31 WARN]:        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12)
[00:04:31 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[00:04:31 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[00:04:31 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[00:04:31 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:938)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:175)
[00:04:31 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:921)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:915)
[00:04:31 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1039)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:817)
[00:04:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268)
[00:04:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by TheHecateII** [comment]
Same problem like #70

**Comment by ClumsyAlien** [comment]
Does this cause any crashing effect on the server?

**Comment by ClumsyAlien** [comment]
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac/files/4398660
